CREATE TABLE [dbo].[Users]
(
	[Id] INT NOT NULL PRIMARY KEY CLUSTERED IDENTITY (1, 1),
	[Guid] UNIQUEIDENTIFIER NOT NULL UNIQUE DEFAULT NEWID(),
	[Username] VARCHAR(50) NOT NULL,
	[Email] VARCHAR(MAX) NOT NULL,
	[CreatedAtDateTimeUTC] DATETIME NOT NULL DEFAULT GETUTCDATE()
)
